spring:
  application:
    name: rupia-auth-service
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG

server:
#  address: 0.0.0.0  #listen to all IP
  port: 8092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true                      # Use IP instead of hostname for registration (useful for containers). It will be your private IP 192.168.60.26:8092
    lease-renewal-interval-in-seconds: 10        # default is 30
    lease-expiration-duration-in-seconds: 30     # default is 90

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

bootstrap:
  super-admin:
    email: ram.cp18113@gmail.com
    password: superadmin

#Spring Boot automatically reads environment variables.
jwt:
  access-secret: ${RUPIA_JWT_SECRET_ACCESS}
  refresh-secret: ${RUPIA_JWT_SECRET_REFRESH}